//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buyer
    {
        public long Id_buyer { get; set; }
        public long Id_Buyer_category { get; set; }
        public Nullable<long> Id_Contact_details { get; set; }
        public long Id_Buyer_status { get; set; }
        public string Login_buyer { get; set; }
        public string Password_buyer { get; set; }
        public Nullable<long> Discount_buyer { get; set; }
        public string Country { get; set; }
        public string City { get; set; }
        public string Address_buyer { get; set; }
    }
}
